### ISSUE TITLE
Adding .hover\:blur-none:hover to filter.css

### ISSUE THREAD

**Issue by Prince-Tirkey** [Priyanshu-kr-gupta/MCASS#102]
Hover over the element removes blur

**Comment by Priyanshu-kr-gupta** [comment]
good news is we are working on the jit(just in time) engine for our library which gonna handle all pseudo classes and arbitrary values.

**Comment by Priyanshu-kr-gupta** [comment]
you can choose any other predefined class to implement.

**Comment by Prince-Tirkey** [comment]
can i add border-collapse  and border-separate to tables.css

**Comment by Priyanshu-kr-gupta** [comment]
sure you can.
create a new issue for that i'll assign it to you.
