### ISSUE TITLE
Adding clear to layout

### ISSUE THREAD

**Issue by ashuyadav-24** [Priyanshu-kr-gupta/MCASS#51]

**Comment by Priyanshu-kr-gupta** [comment]
kindly complete the #50 assigned issue first

**Comment by Priyanshu-kr-gupta** [comment]
clear is already being added in layout please select any other css property sorry for the inconvenience.

**Comment by Priyanshu-kr-gupta** [comment]
i am assigning you the #47  issue kindly work on that

**Comment by ashuyadav-24** [comment]
blur classes are already added by someone..
